"""SQL script generator for Iran inflation data.

Generates SQL INSERT statements that can be executed on any SQL Server.
"""
import os
import pandas as pd
from ..config import OUTPUT_DIR


def export_sql_script(monthly_df: pd.DataFrame | None, yearly_df: pd.DataFrame | None) -> None:
    """Generate SQL script with CREATE TABLE and INSERT statements.

    Files created:
        - data/processed/iran_inflation.sql
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    sql_path = os.path.join(OUTPUT_DIR, "iran_inflation.sql")

    has_monthly = monthly_df is not None and not monthly_df.empty
    has_yearly = yearly_df is not None and not yearly_df.empty

    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("-- Iran Inflation Data - SQL Script\n")
        f.write("-- Generated by Iran Inflation Data Pipeline\n")
        f.write("-- For use with SQL Server\n\n")

        # Yearly table
        if has_yearly:
            f.write("-- Yearly Inflation Data\n")
            f.write("IF OBJECT_ID('dbo.iran_inflation_yearly', 'U') IS NOT NULL\n")
            f.write("    DROP TABLE dbo.iran_inflation_yearly;\n")
            f.write("GO\n\n")
            f.write("CREATE TABLE dbo.iran_inflation_yearly (\n")
            f.write("    year INT PRIMARY KEY,\n")
            f.write("    cpi_index FLOAT,\n")
            f.write("    inflation_yoy_pct FLOAT,\n")
            f.write("    food_inflation_pct FLOAT,\n")
            f.write("    source NVARCHAR(50)\n")
            f.write(");\n")
            f.write("GO\n\n")

            # Insert statements
            for _, row in yearly_df.iterrows():
                cpi = f"{row['cpi_index']:.6f}" if pd.notna(row.get('cpi_index')) else "NULL"
                inflation = f"{row['inflation_yoy_pct']:.6f}" if pd.notna(row.get('inflation_yoy_pct')) else "NULL"
                food = f"{row['food_inflation_pct']:.6f}" if pd.notna(row.get('food_inflation_pct')) else "NULL"
                source = f"'{row['source']}'" if pd.notna(row.get('source')) else "NULL"
                f.write(f"INSERT INTO dbo.iran_inflation_yearly (year, cpi_index, inflation_yoy_pct, food_inflation_pct, source) ")
                f.write(f"VALUES ({int(row['year'])}, {cpi}, {inflation}, {food}, {source});\n")
            f.write("GO\n\n")

        # Monthly table
        if has_monthly:
            f.write("-- Monthly Inflation Data\n")
            f.write("IF OBJECT_ID('dbo.iran_inflation_monthly', 'U') IS NOT NULL\n")
            f.write("    DROP TABLE dbo.iran_inflation_monthly;\n")
            f.write("GO\n\n")
            f.write("CREATE TABLE dbo.iran_inflation_monthly (\n")
            f.write("    date DATE PRIMARY KEY,\n")
            f.write("    year INT,\n")
            f.write("    month INT,\n")
            f.write("    cpi_index FLOAT,\n")
            f.write("    source NVARCHAR(50)\n")
            f.write(");\n")
            f.write("GO\n\n")

            # Insert statements
            for _, row in monthly_df.iterrows():
                date_val = f"'{row['date'].strftime('%Y-%m-%d')}'" if pd.notna(row.get('date')) else "NULL"
                cpi = f"{row['cpi_index']:.6f}" if pd.notna(row.get('cpi_index')) else "NULL"
                source = f"'{row['source']}'" if pd.notna(row.get('source')) else "NULL"
                f.write(f"INSERT INTO dbo.iran_inflation_monthly (date, year, month, cpi_index, source) ")
                f.write(f"VALUES ({date_val}, {int(row['year'])}, {int(row['month'])}, {cpi}, {source});\n")
            f.write("GO\n\n")

        # Create indexes
        if has_yearly:
            f.write("-- Create indexes\n")
            f.write("CREATE INDEX idx_yearly_year ON dbo.iran_inflation_yearly (year);\n")
        if has_monthly:
            f.write("CREATE INDEX idx_monthly_date ON dbo.iran_inflation_monthly (date);\n")
        f.write("GO\n")

    print(f"[SQL Script] Generated SQL script at {sql_path}")
    if has_yearly:
        print(f"  Yearly table: {len(yearly_df)} rows")
    if has_monthly:
        print(f"  Monthly table: {len(monthly_df)} rows")
